### ISSUE TITLE
Question on unconditional sample

### ISSUE THREAD

**Issue by Lucarqi** [CreamyLong/stable-diffusion#11]
I have pretrained a kl-f8 model and unconditional ddpm in my own dataset. So, how can i run inference. Follow the CLI in readme.md, 
```CUDA_VISIBLE_DEVICES=<GPU_ID> python scripts/sample_diffusion.py -r pre_trained_models/ldm/<model_spec>/model.ckpt -l <logdir> -n <\#samples> --batch_size <batch_size> -c <\#ddim steps> -e <\#eta> ```
I can't find sample_diffusion.py in scripts file. So, it is another way to run inference?

**Comment by CreamyLong** [comment]
it is as same as scripts/unconditional_sampling.py
