### ISSUE TITLE
Training the Text-to-Image from scratch

### ISSUE THREAD

**Issue by Awj2021** [CreamyLong/stable-diffusion#4]
hi, Thank you for releasing this repo, it's amazing.  I want to generate 256 * 256 size images to reduce the training time, but if I finetune from SD1.4 (image 512 * 512), the image dimension cannot match. I would like to ask a question whether you once tried to train the text-to-image from scratch? There will be some errors or conflicts? thank you sooooo much!

**Comment by CreamyLong** [comment]
Hi
This happens often due to the wrong config.
I have uploaded the [config of txt2img](https://github.com/CreamyLong/stable-diffusion/blob/master/configs/latent-diffusion/txt2img/txt2img-sdv1.yaml) to fine-tune from the sd version 1.

You could give it a try and share your results.

**Comment by Awj2021** [comment]
@CreamyLong Thank you for your kind reply. I have another question that if I can finetuning the SD-1.5 with 256 * 256 dataset? I noticed that final SD1.1 model was finetuned based on the 256*256 version [SD1.1](https://huggingface.co/CompVis/stable-diffusion-v-1-1-original). So I think I can do it but I am not sure. Thank you!

**Comment by CreamyLong** [comment]
> @CreamyLong Thank you for your kind reply. I have another question that whether I can finetuning the SD-1.5 with 256 * 256 dataset? I noticed that final SD1.1 model was finetuned based on the 256*256 version [SD1.1](https://huggingface.co/CompVis/stable-diffusion-v-1-1-original). So I think I can do it but I am not sure. Thank you!

I think this is ok.
