### ISSUE TITLE
question about requirements and environment.yaml

### ISSUE THREAD

**Issue by Polaris0421** [CreamyLong/stable-diffusion#5]
Thanks for your helpful repo! I had a tough time try to figure out how to use official codes of latent-diffusion.
I notice you change only part of packages' versions in requirements.txt compared to environment.yaml, can I just change corresponding versions in environment.yaml and use it? I don't understand why there are two environment configuration files as rookie.

**Comment by Polaris0421** [comment]
Meanwhile, I notice the setup.py is absent, which is needed when using environment.yaml to configure the environment. I just copy the official setup.py into your project but I'm not sure if this will cause any problem.

**Comment by CreamyLong** [comment]
> Thanks for your helpful repo! I had a tough time try to figure out how to use official codes of latent-diffusion. I notice you change only part of packages' versions in requirements.txt compared to environment.yaml, can I just change corresponding versions in environment.yaml and use it? I don't understand why there are two environment configuration files as rookie.

I built it a bit of time ago, you could try requirements if you have set up the conda environment.
