### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by mwmw7** [CreamyLong/stable-diffusion#6]
I want to train from scratch , but is it working ?

**Comment by CreamyLong** [comment]
Sure, what task are you trying to train from scratch?

**Comment by mwmw7** [comment]
> Sure, what task are you trying to train from scratch?

Our company (https://toonsquare.co/) really wants to create our own foundation model, similar to Stable Diffusion and DALL·E, because we have tons of webtoon images and descriptions

**Comment by CreamyLong** [comment]
I suggest that you can have a look of readme to prepare the data and [config](https://github.com/CreamyLong/stable-diffusion/blob/master/configs/latent-diffusion/txt2img/txt2img-sdv1.yaml)
Then, run the training scripts
`
CUDA_VISIBLE_DEVICES=<GPU_ID> python main.py --base configs/latent-diffusion/<config_spec>.yaml -t --gpus 0,
`

**Comment by mwmw7** [comment]
> > I suggest that you can have a look of readme to prepare the data and [config](https://github.com/CreamyLong/stable-diffusion/blob/master/configs/latent-diffusion/txt2img/txt2img-sdv1.yaml) Then, run the training scripts `CUDA_VISIBLE_DEVICES=<GPU_ID> python main.py --base configs/latent-diffusion/<config_spec>.yaml -t --gpus 0,`
> 
> 
> 
> Thank you for your reply
> 
> 
> 
> but I got these error message, I think there is not "'cls_txt'" in ldm/data/ path
> 
> 
> 
> `Merged modelckpt-cfg: 
> 
> {'target': 'pytorch_lightning.callbacks.ModelCheckpoint', 'params': {'dirpath': 'logs/2024-05-28T20-12-54_txt2img-sdv1/checkpoints', 'filename': '{epoch:06}', 'verbose': True, 'save_last': True, 'monitor': 'val/loss_simple_ema', 'save_top_k': 3}}
> 
> GPU available: True, used: True
> 
> TPU available: False, using: 0 TPU cores
> 
> IPU available: False, using: 0 IPUs
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "main.py", line 701, in <module>
> 
>     data.prepare_data()
> 
>   File "/home/mwmw7/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
> 
>     fn(*args, **kwargs)
> 
>   File "/home/mwmw7/PycharmProjects/toonsquare-creamylong-stable-diffusion/main.py", line 197, in prepare_data
> 
>     instantiate_from_config(data_cfg)
> 
>   File "/home/mwmw7/PycharmProjects/toonsquare-creamylong-stable-diffusion/ldm/util.py", line 129, in instantiate_from_config
> 
>     return get_obj_from_str(config["target"])(**config.get("params", dict()))
> 
>   File "/home/mwmw7/PycharmProjects/toonsquare-creamylong-stable-diffusion/ldm/util.py", line 137, in get_obj_from_str
> 
>     return getattr(importlib.import_module(module, package=None), cls)
> 
>   File "/home/mwmw7/anaconda3/envs/ldm/lib/python3.8/importlib/__init__.py", line 127, in import_module
> 
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
> 
> ModuleNotFoundError: No module named 'ldm.data.cls_txt'
> 
> `
> 
> 

I fixed it

I just rename from "cls_txt" to "custom" I think it needs to be fixed
